"""Dispatch work to Kaggle kernels through the official CLI.

This is the counterpart to notebooks/colab_worker.py, and exists because the
two platforms have opposite control flow:

  Colab   runtimes cannot be connected to from outside, so a worker inside the
          runtime has to poll this server for jobs and stay alive.
  Kaggle  kernels are pushed and run through the API, so this server drives
          them: push, then poll status, then fetch output. Nothing to keep alive.

Everything below is built against values taken from the installed CLI rather
than from docs: the metadata key names and their permitted values are read out
of kaggle/api/kaggle_api_extended.py, and the run states out of the SDK's
KernelWorkerStatus enum.
"""

import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
import time
from typing import Any, Dict, List, Optional

from backend.kaggle_control import _run, cli_status

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

# Permitted values, copied from the CLI's own validation lists
# (valid_push_language_types / valid_push_kernel_types / valid_push_pinning_types).
LANGUAGES = ["python", "r", "rmarkdown"]
KERNEL_TYPES = ["script", "notebook"]
PINNING = ["original", "latest"]

# Terminal states, from the SDK's KernelWorkerStatus enum.
DONE_STATES = {"COMPLETE", "ERROR", "CANCEL_ACKNOWLEDGED"}

JOBS_FILE = os.path.join(os.path.dirname(__file__), "data", "kaggle_jobs.json")
PUSH_TIMEOUT_S = 180

# Kaggle's own validation: "Kernel slug must be at least five characters".
MIN_SLUG_LEN = 5


class DispatchError(RuntimeError):
    pass


def _load_jobs() -> List[Dict[str, Any]]:
    try:
        with open(JOBS_FILE) as f:
            data = json.load(f)
        return data if isinstance(data, list) else []
    except (OSError, json.JSONDecodeError):
        return []


def _save_jobs(jobs: List[Dict[str, Any]]) -> None:
    os.makedirs(os.path.dirname(JOBS_FILE), exist_ok=True)
    tmp = JOBS_FILE + ".part"
    with open(tmp, "w") as f:
        json.dump(jobs[-200:], f, indent=2)
    # Atomic so a crash mid-write can't leave a truncated job list behind.
    os.replace(tmp, JOBS_FILE)


def build_metadata(username: str, slug: str, title: str, code_file: str,
                   enable_gpu: bool = False, enable_tpu: bool = False,
                   dataset_sources: Optional[List[str]] = None) -> Dict[str, Any]:
    """kernel-metadata.json contents.

    enable_internet defaults to False on Kaggle, which would silently break
    every job this project dispatches (they all fetch from S3 / Binance /
    Drive), so it is forced on here rather than left to the caller.
    """
    if len(slug) < MIN_SLUG_LEN:
        raise DispatchError(f"slug must be at least {MIN_SLUG_LEN} characters: {slug!r}")
    if "/" in slug:
        raise DispatchError(f"slug must not contain a slash: {slug!r}")
    return {
        "id": f"{username}/{slug}",
        "title": title,
        "code_file": code_file,
        "language": "python",
        "kernel_type": "script",
        # Private: these scripts carry job parameters and read secrets.
        "is_private": True,
        "enable_gpu": enable_gpu,
        "enable_tpu": enable_tpu,
        "enable_internet": True,
        "dataset_sources": dataset_sources or [],
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }


# The dispatched script. Kaggle kernels only see files in the pushed folder, so
# this is self-contained rather than importing from this repo. Output goes to
# /kaggle/working, which Kaggle persists as the kernel's output and which
# `kernels output` can then download.
_INGEST_SCRIPT = '''"""Auto-generated by backend/kaggle_dispatch.py -- do not edit in place."""
import json, os, subprocess, sys, time

PARAMS = json.loads(r"""__PARAMS__""")
OUT = "/kaggle/working"
started = time.time()
result = {"params": PARAMS}

def sh(*a, **kw):
    return subprocess.run(a, capture_output=True, text=True, **kw)

def pip(*pkgs):
    sh(sys.executable, "-m", "pip", "install", "-q", *pkgs, timeout=900)

kind = PARAMS.get("kind", "aws")

if kind == "aws":
    # AWS public blockchain dataset: no credentials, already Parquet.
    pip("awscli")
    chain, table = PARAMS["chain"], PARAMS["table"]
    dest = os.path.join(OUT, f"chain_{chain}_{table}")
    os.makedirs(dest, exist_ok=True)
    days, total = [], 0
    for day in PARAMS["days"]:
        src = f"s3://aws-public-blockchain/v1.0/{chain}/{table}/date={day}/"
        d = os.path.join(dest, f"date={day}")
        os.makedirs(d, exist_ok=True)
        r = sh("aws", "s3", "cp", src, d, "--recursive", "--no-sign-request", timeout=3600)
        got = sum(os.path.getsize(os.path.join(p, f))
                  for p, _, fs in os.walk(d) for f in fs)
        if got:
            days.append(day); total += got
        else:
            os.rmdir(d) if not os.listdir(d) else None
            result.setdefault("failed_days", []).append({"day": day, "err": r.stderr[-200:]})
    result.update({"days_written": days, "bytes": total,
                   "mb_per_s": round(total / 1024**2 / max(1e-6, time.time() - started), 1)})

elif kind == "binance":
    pip("polars")
    import polars as pl, urllib.request, zipfile, io
    sym, interval = PARAMS["symbol"].upper(), PARAMS["interval"]
    dest = os.path.join(OUT, f"market_{sym.lower()}_{interval}")
    os.makedirs(dest, exist_ok=True)
    written, rows = [], 0
    for ym in PARAMS["months"]:
        url = (f"https://data.binance.vision/data/spot/monthly/klines/"
               f"{sym}/{interval}/{sym}-{interval}-{ym}.zip")
        try:
            raw = urllib.request.urlopen(url, timeout=180).read()
        except Exception as e:
            result.setdefault("failed_months", []).append({"month": ym, "err": str(e)[:200]})
            continue
        with zipfile.ZipFile(io.BytesIO(raw)) as z:
            name = z.namelist()[0]
            df = pl.read_csv(z.read(name), has_header=False, new_columns=[
                "open_time","open","high","low","close","volume","close_time",
                "quote_volume","trades","taker_buy_base","taker_buy_quote","ignore"])
        # Binance switched open_time to microseconds partway through, so detect
        # per row by magnitude instead of assuming one unit for the whole file.
        df = df.with_columns(
            pl.when(pl.col("open_time") > 1e15)
              .then(pl.col("open_time") // 1000)
              .otherwise(pl.col("open_time")).alias("open_time"))
        p = os.path.join(dest, f"{sym}-{interval}-{ym}.parquet")
        df.write_parquet(p, compression="zstd")
        written.append(ym); rows += df.height
    result.update({"months_written": written, "rows": rows})

else:
    result["error"] = f"unknown kind: {kind}"

result["elapsed_s"] = round(time.time() - started, 1)
result["specs"] = {"cpu": os.cpu_count()}
try:
    result["specs"]["ram_gb"] = round(
        os.sysconf("SC_PAGE_SIZE") * os.sysconf("SC_PHYS_PAGES") / 1024**3, 1)
except Exception:
    pass

with open(os.path.join(OUT, "result.json"), "w") as f:
    json.dump(result, f, indent=2)
print("__RESULT__" + json.dumps(result))
'''


def render_script(params: Dict[str, Any]) -> str:
    # json.dumps twice so the payload survives being embedded in the script.
    return _INGEST_SCRIPT.replace("__PARAMS__", json.dumps(params).replace('"""', '\\"\\"\\"'))


_REF_RE = re.compile(r"(?:ref|url)\D*([\w-]+/[\w-]+)", re.I)
_VERSION_RE = re.compile(r"version\s*(\d+)", re.I)


def dispatch(username: str, slug: str, params: Dict[str, Any], *,
             title: Optional[str] = None, timeout: Optional[str] = None,
             enable_gpu: bool = False, enable_tpu: bool = False) -> Dict[str, Any]:
    """Pushes one job and records it. Returns immediately -- Kaggle queues it."""
    st = cli_status()
    if not st["installed"]:
        raise DispatchError("kaggle CLI not installed")
    if not st["authenticated"]:
        raise DispatchError(st["auth_hint"] or "kaggle CLI not authenticated")

    folder = tempfile.mkdtemp(prefix="kaggle-job-")
    try:
        code_file = "job.py"
        with open(os.path.join(folder, code_file), "w") as f:
            f.write(render_script(params))
        meta = build_metadata(username, slug, title or slug, code_file,
                              enable_gpu=enable_gpu, enable_tpu=enable_tpu)
        with open(os.path.join(folder, "kernel-metadata.json"), "w") as f:
            json.dump(meta, f, indent=2)

        args = ["kernels", "push", "-p", folder]
        if timeout:
            # The CLI accepts duration strings ("2h", "30s", "2h30s"), not just
            # a bare number of seconds.
            args += ["-t", str(timeout)]
        r = _run(args, timeout=PUSH_TIMEOUT_S)
        text = (r["out"] + r["err"]).strip()
        if not r["ok"]:
            raise DispatchError(text[:400] or "kernels push failed")

        ref_m = _REF_RE.search(text)
        ver_m = _VERSION_RE.search(text)
        job = {
            "ref": ref_m.group(1) if ref_m else f"{username}/{slug}",
            "version": int(ver_m.group(1)) if ver_m else None,
            "slug": slug,
            "params": params,
            "pushed_at": time.time(),
            "status": "QUEUED",
            "push_output": text[:400],
        }
        jobs = _load_jobs()
        jobs.append(job)
        _save_jobs(jobs)
        logging.info(f"dispatched kaggle kernel {job['ref']}")
        return job
    finally:
        shutil.rmtree(folder, ignore_errors=True)


_STATUS_RE = re.compile(r'"?(QUEUED|RUNNING|COMPLETE|ERROR|CANCEL_REQUESTED|'
                        r'CANCEL_ACKNOWLEDGED|NEW_SCRIPT)"?', re.I)


def status(ref: str) -> Dict[str, Any]:
    r = _run(["kernels", "status", ref], timeout=60)
    text = (r["out"] + r["err"]).strip()
    m = _STATUS_RE.search(text)
    state = m.group(1).upper() if m else None
    return {"ref": ref, "state": state, "done": state in DONE_STATES,
            "raw": text[:400], "ok": r["ok"]}


def refresh_jobs() -> List[Dict[str, Any]]:
    """Polls non-terminal jobs and persists whatever changed."""
    jobs = _load_jobs()
    changed = False
    for j in jobs:
        if j.get("status") in DONE_STATES:
            continue
        s = status(j["ref"])
        if s["state"] and s["state"] != j.get("status"):
            j["status"] = s["state"]
            j["checked_at"] = time.time()
            changed = True
    if changed:
        _save_jobs(jobs)
    return jobs


def fetch_output(ref: str, dest_dir: str) -> Dict[str, Any]:
    """Downloads a finished kernel's output and reads back result.json."""
    os.makedirs(dest_dir, exist_ok=True)
    r = _run(["kernels", "output", ref, "-p", dest_dir, "-o"], timeout=900)
    text = (r["out"] + r["err"]).strip()
    out: Dict[str, Any] = {"ref": ref, "ok": r["ok"], "dest": dest_dir, "raw": text[:400]}
    rj = os.path.join(dest_dir, "result.json")
    if os.path.exists(rj):
        try:
            with open(rj) as f:
                out["result"] = json.load(f)
        except json.JSONDecodeError as e:
            out["result_error"] = str(e)
    files = [os.path.join(p, f) for p, _, fs in os.walk(dest_dir) for f in fs]
    out["files"] = len(files)
    out["bytes"] = sum(os.path.getsize(f) for f in files)
    return out


def logs(ref: str) -> Dict[str, Any]:
    r = _run(["kernels", "logs", ref], timeout=120)
    return {"ref": ref, "ok": r["ok"], "logs": (r["out"] + r["err"])[-4000:]}


def list_jobs() -> List[Dict[str, Any]]:
    return list(reversed(_load_jobs()))
