"""Dispatch work to Kaggle kernels through the official CLI.

This is the counterpart to notebooks/colab_worker.py, and exists because the
two platforms have opposite control flow:

  Colab   runtimes cannot be connected to from outside, so a worker inside the
          runtime has to poll this server for jobs and stay alive.
  Kaggle  kernels are pushed and run through the API, so this server drives
          them: push, then poll status, then fetch output. Nothing to keep alive.

Everything below is built against values taken from the installed CLI rather
than from docs: the metadata key names and their permitted values are read out
of kaggle/api/kaggle_api_extended.py, and the run states out of the SDK's
KernelWorkerStatus enum.
"""

import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
import time
from typing import Any, Dict, List, Optional

from backend.kaggle_control import _run, cli_status

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

# Permitted values, copied from the CLI's own validation lists
# (valid_push_language_types / valid_push_kernel_types / valid_push_pinning_types).
LANGUAGES = ["python", "r", "rmarkdown"]
KERNEL_TYPES = ["script", "notebook"]
PINNING = ["original", "latest"]

# Terminal states, from the SDK's KernelWorkerStatus enum.
DONE_STATES = {"COMPLETE", "ERROR", "CANCEL_ACKNOWLEDGED"}

JOBS_FILE = os.path.join(os.path.dirname(__file__), "data", "kaggle_jobs.json")
PUSH_TIMEOUT_S = 180

# Kaggle's own validation: "Kernel slug must be at least five characters".
MIN_SLUG_LEN = 5


class DispatchError(RuntimeError):
    pass


def _load_jobs() -> List[Dict[str, Any]]:
    try:
        with open(JOBS_FILE) as f:
            data = json.load(f)
        return data if isinstance(data, list) else []
    except (OSError, json.JSONDecodeError):
        return []


# Params that carry a live credential. They have to reach the kernel, but they
# must never reach the job log: GitHub's secret scanner caught exactly this,
# blocking a push because a persisted drive_access_token sat in kaggle_jobs.json.
SECRET_PARAM_KEYS = ("drive_access_token", "access_token", "token", "secret",
                     "client_secret", "refresh_token", "password", "api_key")


def _redact(params: Dict[str, Any]) -> Dict[str, Any]:
    """Copy of the params with credential values replaced by a marker."""
    out = {}
    for k, v in (params or {}).items():
        if any(s in k.lower() for s in SECRET_PARAM_KEYS):
            out[k] = f"<redacted {len(str(v))} chars>"
        else:
            out[k] = v
    return out


def _save_jobs(jobs: List[Dict[str, Any]]) -> None:
    os.makedirs(os.path.dirname(JOBS_FILE), exist_ok=True)
    tmp = JOBS_FILE + ".part"
    with open(tmp, "w") as f:
        json.dump(jobs[-200:], f, indent=2)
    # Atomic so a crash mid-write can't leave a truncated job list behind.
    os.replace(tmp, JOBS_FILE)


def build_metadata(username: str, slug: str, title: str, code_file: str,
                   enable_gpu: bool = False, enable_tpu: bool = False,
                   dataset_sources: Optional[List[str]] = None) -> Dict[str, Any]:
    """kernel-metadata.json contents.

    enable_internet defaults to False on Kaggle, which would silently break
    every job this project dispatches (they all fetch from S3 / Binance /
    Drive), so it is forced on here rather than left to the caller.
    """
    if len(slug) < MIN_SLUG_LEN:
        raise DispatchError(f"slug must be at least {MIN_SLUG_LEN} characters: {slug!r}")
    if "/" in slug:
        raise DispatchError(f"slug must not contain a slash: {slug!r}")
    return {
        "id": f"{username}/{slug}",
        "title": title,
        "code_file": code_file,
        "language": "python",
        "kernel_type": "script",
        # Private: these scripts carry job parameters and read secrets.
        "is_private": True,
        "enable_gpu": enable_gpu,
        "enable_tpu": enable_tpu,
        "enable_internet": True,
        "dataset_sources": dataset_sources or [],
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }


# The dispatched script. Kaggle kernels only see files in the pushed folder, so
# this is self-contained rather than importing from this repo. Output goes to
# /kaggle/working, which Kaggle persists as the kernel's output and which
# `kernels output` can then download.
_INGEST_SCRIPT = '''"""Auto-generated by backend/kaggle_dispatch.py -- do not edit in place."""
import json, os, subprocess, sys, time

PARAMS = json.loads(r"""__PARAMS__""")
OUT = "/kaggle/working"
started = time.time()
result = {"params": PARAMS}

def sh(*a, **kw):
    return subprocess.run(a, capture_output=True, text=True, **kw)

def pip(*pkgs):
    sh(sys.executable, "-m", "pip", "install", "-q", *pkgs, timeout=900)

kind = PARAMS.get("kind", "aws")

if kind == "aws":
    # AWS public blockchain dataset: no credentials, already Parquet.
    pip("awscli")
    # Timed from here, not from script start: the pip install above took most of
    # the earlier run's wall clock and dragged the reported rate down to 0.3 MB/s
    # for a transfer that actually takes seconds.
    dl_started = time.time()
    chain, table = PARAMS["chain"], PARAMS["table"]
    dest = os.path.join(OUT, f"chain_{chain}_{table}")
    os.makedirs(dest, exist_ok=True)
    days, total = [], 0
    for day in PARAMS["days"]:
        src = f"s3://aws-public-blockchain/v1.0/{chain}/{table}/date={day}/"
        d = os.path.join(dest, f"date={day}")
        os.makedirs(d, exist_ok=True)
        r = sh("aws", "s3", "cp", src, d, "--recursive", "--no-sign-request", timeout=3600)
        got = sum(os.path.getsize(os.path.join(p, f))
                  for p, _, fs in os.walk(d) for f in fs)
        if got:
            days.append(day); total += got
        else:
            os.rmdir(d) if not os.listdir(d) else None
            result.setdefault("failed_days", []).append({"day": day, "err": r.stderr[-200:]})
    dl_elapsed = max(1e-6, time.time() - dl_started)
    result.update({"days_written": days, "bytes": total,
                   "download_seconds": round(dl_elapsed, 2),
                   "mb_per_s": round(total / 1024**2 / dl_elapsed, 1)})

elif kind == "binance":
    pip("polars")
    import polars as pl, urllib.request, zipfile, io
    sym, interval = PARAMS["symbol"].upper(), PARAMS["interval"]
    dest = os.path.join(OUT, f"market_{sym.lower()}_{interval}")
    os.makedirs(dest, exist_ok=True)
    written, rows = [], 0
    for ym in PARAMS["months"]:
        url = (f"https://data.binance.vision/data/spot/monthly/klines/"
               f"{sym}/{interval}/{sym}-{interval}-{ym}.zip")
        try:
            raw = urllib.request.urlopen(url, timeout=180).read()
        except Exception as e:
            result.setdefault("failed_months", []).append({"month": ym, "err": str(e)[:200]})
            continue
        with zipfile.ZipFile(io.BytesIO(raw)) as z:
            name = z.namelist()[0]
            df = pl.read_csv(z.read(name), has_header=False, new_columns=[
                "open_time","open","high","low","close","volume","close_time",
                "quote_volume","trades","taker_buy_base","taker_buy_quote","ignore"])
        # Binance switched open_time to microseconds partway through, so detect
        # per row by magnitude instead of assuming one unit for the whole file.
        df = df.with_columns(
            pl.when(pl.col("open_time") > 1e15)
              .then(pl.col("open_time") // 1000)
              .otherwise(pl.col("open_time")).alias("open_time"))
        p = os.path.join(dest, f"{sym}-{interval}-{ym}.parquet")
        df.write_parquet(p, compression="zstd")
        written.append(ym); rows += df.height
    result.update({"months_written": written, "rows": rows})

elif kind == "uploadbench":
    # Pure upload throughput. The 5.9 MB ingest run reported 1.53 MB/s, but that
    # is one resumable chunk: session-create plus a single PUT, so per-request
    # latency dominates and the figure says nothing about sustained bandwidth.
    # Generating the payload in-runtime keeps the download side out of it.
    mb = int(PARAMS.get("mb", 200))
    dest = os.path.join(OUT, "uploadbench")
    os.makedirs(dest, exist_ok=True)
    path = os.path.join(dest, f"bench_{mb}mb.bin")
    t0 = time.time()
    with open(path, "wb") as f:
        # Incompressible, so Drive can't flatter the number by compressing it.
        for _ in range(mb):
            f.write(os.urandom(1024 * 1024))
    result["generate_seconds"] = round(time.time() - t0, 2)
    result["payload_mb"] = mb

elif kind == "drivecheck":
    # Answers "can a Kaggle kernel reach our Drive?" with measurements rather
    # than assumption. Kaggle has no FUSE mount at all (google.colab.drive
    # raises KeyError here), so the REST path is the only one that can work --
    # this proves whether it does, and whether a token can be injected.
    import urllib.request, urllib.error, socket
    checks = {}

    def probe(name, url):
        t0 = time.time()
        try:
            urllib.request.urlopen(url, timeout=20)
            checks[name] = {"status": 200, "ms": round((time.time() - t0) * 1000, 1)}
        except urllib.error.HTTPError as e:
            # 401 is the expected, healthy answer without a token: it proves the
            # request reached Google and was understood.
            checks[name] = {"status": e.code, "ms": round((time.time() - t0) * 1000, 1),
                            "body": e.read().decode(errors="ignore")[:160]}
        except Exception as e:
            checks[name] = {"error": str(e)[:200]}

    probe("drive_api", "https://www.googleapis.com/drive/v3/about?fields=storageQuota")
    probe("oauth_token_endpoint", "https://oauth2.googleapis.com/token")
    checks["egress_open"] = any(c.get("status") for c in checks.values())

    # Is the documented secret-injection mechanism actually present?
    try:
        from kaggle_secrets import UserSecretsClient
        checks["kaggle_secrets"] = {"available": True,
                                    "methods": [m for m in dir(UserSecretsClient)
                                                if not m.startswith("_")]}
    except Exception as e:
        checks["kaggle_secrets"] = {"available": False, "error": str(e)[:200]}

    # Is Colab's mount module present here at all? Expected: no.
    try:
        import google.colab  # noqa: F401
        checks["google_colab_module"] = True
    except Exception as e:
        checks["google_colab_module"] = f"absent ({type(e).__name__})"

    # Throughput to Google's own network, for comparison with Colab's 185.9 MB/s.
    t0 = time.time()
    r = sh("curl", "-s", "-o", "/dev/null", "-w", "%{speed_download}",
           "https://storage.googleapis.com/gcp-public-data-landsat/index.csv.gz", timeout=180)
    try:
        checks["gcs_download_MBps"] = round(float(r.stdout.strip()) / 1024 / 1024, 1)
    except Exception:
        checks["gcs_download_MBps"] = None

    result["checks"] = checks

else:
    result["error"] = f"unknown kind: {kind}"

# Upload to Drive if a folder was requested and the secret is present. The
# secret is read from Kaggle Secrets, never embedded in this script -- the
# script is stored in the kernel and would leak with it.
if PARAMS.get("drive_folder"):
    raw = None
    tok = None
    # A short-lived access token may be passed in the params instead. It is only
    # for one-off measurement: it expires in about an hour and cannot be used to
    # mint another, so leaving it in the stored kernel source is bounded in a way
    # a refresh token never would be. Production paths use Secrets.
    if PARAMS.get("drive_access_token"):
        tok = PARAMS["drive_access_token"]
    else:
        try:
            from kaggle_secrets import UserSecretsClient
            raw = UserSecretsClient().get_secret(PARAMS.get("secret_name", "DRIVE_OAUTH_JSON"))
        except Exception as e:
            result["drive"] = {"error": f"could not read secret: {str(e)[:200]}"}
    if raw or tok:
        try:
            import drive_rest
            if tok is None:
                tok = drive_rest.token_from_secret(raw)
            targets = [d for d in os.listdir(OUT)
                       if os.path.isdir(os.path.join(OUT, d))]
            ups = []
            for d in targets:
                ups.append(drive_rest.upload_tree(
                    tok, os.path.join(OUT, d), f"{PARAMS['drive_folder']}/{d}"))
            result["drive"] = {
                "uploads": ups,
                "total_bytes": sum(u["bytes"] for u in ups),
                "total_files": sum(u["files"] for u in ups),
                "mb_per_s": round(sum(u["bytes"] for u in ups) / 1024**2
                                  / max(1e-6, sum(u["seconds"] for u in ups)), 2),
            }
            q = drive_rest.about(tok).get("storageQuota", {})
            result["drive"]["quota"] = {k: q.get(k) for k in ("limit", "usage")}
        except Exception as e:
            result["drive"] = {"error": str(e)[:300]}

result["elapsed_s"] = round(time.time() - started, 1)
result["specs"] = {"cpu": os.cpu_count()}
try:
    result["specs"]["ram_gb"] = round(
        os.sysconf("SC_PAGE_SIZE") * os.sysconf("SC_PHYS_PAGES") / 1024**3, 1)
except Exception:
    pass

with open(os.path.join(OUT, "result.json"), "w") as f:
    json.dump(result, f, indent=2)
print("__RESULT__" + json.dumps(result))
'''


DRIVE_REST_PATH = os.path.join(os.path.dirname(__file__), "drive_rest.py")


def render_script(params: Dict[str, Any]) -> str:
    """Builds the self-contained kernel script.

    drive_rest.py is embedded rather than shipped alongside: `kernels push`
    uploads the folder, but Kaggle only treats code_file as the kernel source,
    so a sibling module is not importable in the runtime -- measured, the job
    failed with "No module named 'drive_rest'". The repo still holds exactly one
    copy; it is materialised into the script at dispatch time.
    """
    with open(DRIVE_REST_PATH) as f:
        module_src = f.read()
    body = _INGEST_SCRIPT.replace(
        "__PARAMS__", json.dumps(params).replace('"""', '\\"\\"\\"'))
    return (
        "# --- begin embedded backend/drive_rest.py (do not edit here) ---\n"
        "import sys as _sys, types as _types\n"
        "_m = _types.ModuleType('drive_rest')\n"
        "_m.__dict__['__name__'] = 'drive_rest'\n"
        f"exec(compile({module_src!r}, 'drive_rest.py', 'exec'), _m.__dict__)\n"
        "_sys.modules['drive_rest'] = _m\n"
        "# --- end embedded module ---\n\n"
        + body
    )


# Prefer the URL Kaggle prints, because the slug it actually used may differ
# from the one we asked for (see _slugify below).
_URL_REF_RE = re.compile(r"kaggle\.com/(?:code|kernels/scripts)/([\w-]+/[\w-]+)", re.I)
_REF_RE = re.compile(r"(?:ref|url)\D*([\w-]+/[\w-]+)", re.I)
_VERSION_RE = re.compile(r"version\s*(\d+)", re.I)


def _slugify(title: str) -> str:
    """Kaggle's slug derivation, needed because it wins over metadata `id`.

    Observed: pushing id=yjh980/cq-drivecheck with title="ChainQuant drive
    connectivity check" created yjh980/chainquant-drive-connectivity-check, and
    every later `kernels status`/`output` call on the requested id failed with
    "Permission 'kernels.get' was denied". The push does warn -- "Your kernel
    title does not resolve to the specified id" -- so the two must be kept
    consistent rather than set independently.
    """
    out = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return re.sub(r"-{2,}", "-", out)


def dispatch(username: str, slug: str, params: Dict[str, Any], *,
             title: Optional[str] = None, timeout: Optional[int] = None,
             enable_gpu: bool = False, enable_tpu: bool = False) -> Dict[str, Any]:
    """Pushes one job and records it. Returns immediately -- Kaggle queues it."""
    st = cli_status()
    if not st["installed"]:
        raise DispatchError("kaggle CLI not installed")
    if not st["authenticated"]:
        raise DispatchError(st["auth_hint"] or "kaggle CLI not authenticated")

    folder = tempfile.mkdtemp(prefix="kaggle-job-")
    try:
        code_file = "job.py"
        with open(os.path.join(folder, code_file), "w") as f:
            f.write(render_script(params))
        # `kernels push` uploads the whole folder, so the Drive client rides
        # along as a real module rather than being string-inlined. One source of
        # truth shared with the Colab worker.
        shutil.copy(os.path.join(os.path.dirname(__file__), "drive_rest.py"),
                    os.path.join(folder, "drive_rest.py"))
        # If the caller's title would slugify to something else, Kaggle would
        # silently file the kernel under that instead, orphaning our handle.
        effective_title = title or slug
        if _slugify(effective_title) != slug:
            logging.info(
                f"title {effective_title!r} slugifies to {_slugify(effective_title)!r}, "
                f"not {slug!r}; using the slug as the title so the ref stays valid")
            effective_title = slug
        meta = build_metadata(username, slug, effective_title, code_file,
                              enable_gpu=enable_gpu, enable_tpu=enable_tpu)
        with open(os.path.join(folder, "kernel-metadata.json"), "w") as f:
            json.dump(meta, f, indent=2)

        args = ["kernels", "push", "-p", folder]
        if timeout:
            # Seconds only. `kernels push -t` is argparse type=int: passing a
            # duration string such as "15m" is rejected outright. (Other
            # commands do accept "1h"/"30s" forms -- this one does not.)
            args += ["-t", str(int(timeout))]
        r = _run(args, timeout=PUSH_TIMEOUT_S)
        text = (r["out"] + r["err"]).strip()
        if not r["ok"]:
            raise DispatchError(text[:400] or "kernels push failed")

        url_m = _URL_REF_RE.search(text)
        ref_m = _REF_RE.search(text)
        ver_m = _VERSION_RE.search(text)
        job = {
            # URL first: it is what Kaggle actually created.
            "ref": url_m.group(1) if url_m else (ref_m.group(1) if ref_m else f"{username}/{slug}"),
            "version": int(ver_m.group(1)) if ver_m else None,
            "slug": slug,
            # Redacted: this record is written to disk and read by the dashboard.
            "params": _redact(params),
            "pushed_at": time.time(),
            "status": "QUEUED",
            "push_output": text[:400],
        }
        if "does not resolve to the specified id" in text:
            # Should be unreachable now, but surface it rather than hide it.
            job["warning"] = "kaggle reported a title/id slug mismatch"
        jobs = _load_jobs()
        jobs.append(job)
        _save_jobs(jobs)
        logging.info(f"dispatched kaggle kernel {job['ref']}")
        return job
    finally:
        shutil.rmtree(folder, ignore_errors=True)


_STATUS_RE = re.compile(r'"?(QUEUED|RUNNING|COMPLETE|ERROR|CANCEL_REQUESTED|'
                        r'CANCEL_ACKNOWLEDGED|NEW_SCRIPT)"?', re.I)


def status(ref: str) -> Dict[str, Any]:
    r = _run(["kernels", "status", ref], timeout=60)
    text = (r["out"] + r["err"]).strip()
    m = _STATUS_RE.search(text)
    state = m.group(1).upper() if m else None
    return {"ref": ref, "state": state, "done": state in DONE_STATES,
            "raw": text[:400], "ok": r["ok"]}


def refresh_jobs() -> List[Dict[str, Any]]:
    """Polls non-terminal jobs and persists whatever changed."""
    jobs = _load_jobs()
    changed = False
    for j in jobs:
        if j.get("status") in DONE_STATES:
            continue
        s = status(j["ref"])
        if s["state"] and s["state"] != j.get("status"):
            j["status"] = s["state"]
            j["checked_at"] = time.time()
            changed = True
    if changed:
        _save_jobs(jobs)
    return jobs


def fetch_output(ref: str, dest_dir: str) -> Dict[str, Any]:
    """Downloads a finished kernel's output and reads back result.json."""
    os.makedirs(dest_dir, exist_ok=True)
    r = _run(["kernels", "output", ref, "-p", dest_dir, "-o"], timeout=900)
    text = (r["out"] + r["err"]).strip()
    out: Dict[str, Any] = {"ref": ref, "ok": r["ok"], "dest": dest_dir, "raw": text[:400]}
    rj = os.path.join(dest_dir, "result.json")
    if os.path.exists(rj):
        try:
            with open(rj) as f:
                out["result"] = json.load(f)
        except json.JSONDecodeError as e:
            out["result_error"] = str(e)
    files = [os.path.join(p, f) for p, _, fs in os.walk(dest_dir) for f in fs]
    out["files"] = len(files)
    out["bytes"] = sum(os.path.getsize(f) for f in files)
    return out


def logs(ref: str) -> Dict[str, Any]:
    r = _run(["kernels", "logs", ref], timeout=120)
    return {"ref": ref, "ok": r["ok"], "logs": (r["out"] + r["err"])[-4000:]}


def list_jobs() -> List[Dict[str, Any]]:
    return list(reversed(_load_jobs()))
